### ISSUE TITLE
very laggy options animation

### ISSUE THREAD

**Issue by steve47457** [GrapheneOS/Camera#104]
![laggy animation popup](https://user-images.githubusercontent.com/97707996/152025461-a1a7a78f-b10c-4532-abf1-bb9b5594bc43.gif)
very laggy animation (low fps) for options

**Comment by thestinger** [comment]
Unable to reproduce this. You'll need to give more details on the phone. It may be too slow to do animations smoothly when using the camera.

**Comment by Zanthed** [comment]
The Android Studio Emulator is not a good reference as it's not great in real-world performance. It's meant for basic testing and development.

Please use a real device and see if the issue persists.

**Comment by steve47457** [comment]
@Zanthed I have the same issue on my phone. I just used the emulator for demonstration purposes

**Comment by steve47457** [comment]
@thestinger  Samsung Galaxy A03s

**Comment by thestinger** [comment]
I think it's simply an issue with using the camera on low-end phones. They're struggling to simply support the modern Camera2 API including the preview and can't do smooth animations at the same time. I don't think we can do anything about this. We're just using a standard animation library.
