### ISSUE TITLE
slow camera resumption

### ISSUE THREAD

**Issue by steve47457** [GrapheneOS/Camera#106]
when the user returns to the app, the camera takes a long time (few seconds) to update. This doesn't happen in other camera apps

steps to reproduce:
1. open app
2. turn off screen
3. re-open screen

OR:

1. open app
2. tap home button
3. return to app

Samsung Galaxy A03s

**Comment by thestinger** [comment]
This is going to be improved over time and isn't a specific issue. Most of it is up to CameraX and CameraX is more oriented towards modern high end devices. It enables a fair bit of stuff that takes more time than other camera implementations. Some of the extra time is spent dealing with CameraX vendor extensions, etc. too.
