### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by 007chaand** [GrapheneOS/Camera#109]
Please add support RAW and manual mode 🙏

**Comment by thestinger** [comment]
See https://github.com/GrapheneOS/Camera/issues/14 for RAW support. You'll need to clarify which features you want from a manual/professional mode since they would need to be separately implemented.

**Comment by 007chaand** [comment]
> See #14 for RAW support. You'll need to clarify which features you want from a manual/professional mode since they would need to be separately implemented.

I mean full manual control:
Manual focus
Manual iso
Manual exposure
Manual white balance
Raw/DNG support

**Comment by thestinger** [comment]
It needs to be requesting separated from RAW support and what's being requested needs to be more specific.

**Comment by locustangerine** [comment]
What's the status on creating a feature request for a new camera mode that has 007chaand's requested features? A good reference is the stock camera app for the OnePlus 6: sliders and wheels that allow Auto or Manual settings for focus, white balance, shutter speed, ISO, etc.

![IMG_20220308_141938_742](https://user-images.githubusercontent.com/80425606/157326912-240dc4f8-2ea8-4a9e-825a-aae3fff3db1b.jpg)

**Comment by 007chaand** [comment]
Yes that exactly what we want 😊
By the way I love graphene camera app
