### ISSUE TITLE
[Feature request] allow third-party gallery apps

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/Camera#111]
Please allow third-party gallery apps. 
I like to use the simple gallery app to display the images and so that I have a unified recycle bin.

**Comment by Zanthed** [comment]
You already can use third-party gallery apps just fine. Need to clarify what you're asking.

**Comment by Zanthed** [comment]
Are you asking about using a third-party gallery app instead of the built-in app gallery?

**Comment by BluePixel4k** [comment]
Yes exactly :)

**Comment by thestinger** [comment]
This can't realistically be supported due to SAF, latency required to fetch all of the URLs to pass to the app, etc. Our in-app gallery is not simple showing all photos in a specific directory. It's showing the photos taken by the app for that storage location tracked by MediaStore / SAF.
