### ISSUE TITLE
[bug] app is not using all the screen and hides part of the settings button

### ISSUE THREAD

**Issue by williamdes** [GrapheneOS/Camera#122]
![Screenshot_2022-02-26-09-11-45-056_app grapheneos camera](https://user-images.githubusercontent.com/7784660/155835764-da3e76d2-7293-4fba-9fbe-6b66bcdd555d.jpg)

Here is the screenshot of exactly what I see.
I am using a Redmi Note 10 Pro. So if you do not do support for other devices you can close this issue.

The app should someway understand that I have a large screen and not render some kind of black overlay that hide the settings button

Android: 11

**Comment by thestinger** [comment]
> So if you do not do support for other devices you can close this issue.

We do want to support other devices. We just don't want to have to write device-specific code and we're leaving that up to CameraX. We can work on addressing this issue.

**Comment by empratyush** [comment]
hey @williamdes  i think you are having this issue because you are using "hide notch" feature from MIUI which works in non-standard way.

there is standard api for checking available screen real state (for third party devs) but somehow MIUI is breaking standard api to provide "hide notch" feature. Try tunring "hide notch" feature off.

**Comment by williamdes** [comment]
> hey @williamdes i think you are having this issue because you are using "hide notch" feature from MIUI which works in non-standard way.
> 
> there is standard api for checking available screen real state (for third party devs) but somehow MIUI is breaking standard api to provide "hide notch" feature. Try tunring "hide notch" feature off.
> 
> edit: [MIUI have same issue in other mi devices too ](https://drive.google.com/file/d/1DLH8p0VQdyFwFnGhQ9MxBEVkK_QXavM7/view?usp=sharing)

You are right, that said I do no like the notch thing so for now disabling will not be a solution
But thank you for feed back this is interesting. I hope you can find a fix someway. If not that not to much of a problem as I can click the menu button and there is nothing more to see behind.

**Comment by empratyush** [comment]
>  I hope you can find a fix someway. 

We don't want to write device-specific code when oem deliberately break standard api compatibility . standard api exist for a reason.

**Comment by williamdes** [comment]
Just updated to Android 12/MIUI 13 and it is fixed! 

![Screenshot_2022-03-26-08-59-33-950_app grapheneos camera play](https://user-images.githubusercontent.com/7784660/160230559-b81c3f38-9e69-4f5d-aaf7-58accbbd4350.jpg)
