### ISSUE TITLE
[Feature request] front camera "flash"

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/Camera#123]
In other camera apps there is a "flash" for the front camera mode, which is realized by brightening the screen and changing the GUI color to creamy white.

Would be great if that can be added to this app too, thanks.

GCam example:
![GCam_flash](https://user-images.githubusercontent.com/77979781/155880915-05f9e105-f44b-44f3-910c-e95b2f08da06.png)

**Comment by Zanthed** [comment]
Already exists. It's called "Self-Illumination".

**Comment by BluePixel4k** [comment]
Oh thank you, I overlooked that. Would it be conceivable that you add the function to the flash function, instead of the separate checkbox? That would be more intuitive from my point of view.

Currently there is a message that the flash is is unavailable in the current mode.

![Cam_flash_v2](https://user-images.githubusercontent.com/77979781/155972928-e2563f44-45b3-4814-aad6-f0c14a5f5297.png)
