### ISSUE TITLE
App size is smaller 

### ISSUE THREAD

**Issue by cyberpunkme** [GrapheneOS/Camera#134]
Can u provide another direct link for me 
[Look at this ](https://telegra.ph/Is-this-only-for-me-03-06)

**Comment by thestinger** [comment]
That's the correct size, The units are different.

**Comment by thestinger** [comment]
You can install this app from the Play Store or from our app repository. The one in our app repository is the same as the one published on GitHub.

https://github.com/GrapheneOS/Apps/releases/tag/4

Our app repository will update itself and this app once you install both.

**Comment by cyberpunkme** [comment]
![Screenshot_20220306-091833_Package installer](https://user-images.githubusercontent.com/85578224/156908412-91c22873-0760-485f-b7da-360c07515320.jpg)

**Comment by thestinger** [comment]
The app requires Android 10+.

**Comment by cyberpunkme** [comment]
Heyy brother please provide appcenter link

**Comment by cyberpunkme** [comment]
> The app requires Android 10+.

Ohh ok bye

**Comment by thestinger** [comment]
There's a variant of the app on the Play Store and the standalone variant in our app repository. The standalone variant is what's published on GitHub.
