### ISSUE TITLE
Switching to QR Scan freezes camera

### ISSUE THREAD

**Issue by gGkAC3qfszbdViFkw4Fk9ooS2u** [GrapheneOS/Camera#143]
1. Open Camera
2. Switch to QR Scan
3. Camera viewer freezes

Device: OnePlus 6

https://user-images.githubusercontent.com/95468948/157296310-701d9f8f-31c6-457e-af4a-b25aafd088da.mp4

**Comment by thestinger** [comment]
We need to know which device you're on since this is certainly a device specific bug and isn't occurring for the vast majority of users.

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
> 

Issue updated to reflect requested information.

**Comment by thestinger** [comment]
@gGkAC3qfszbdViFkw4Fk9ooS2u Is it the stock OS on the OnePlus 6 or something else?

**Comment by gGkAC3qfszbdViFkw4Fk9ooS2u** [comment]
No, this is LineageOS.

Build Number: lineage_enchilada-userdebug 11 RQ3A.211001.001 10040210
