### ISSUE TITLE
QR scanner doesn't linkify custom URL schemes correctly

### ISSUE THREAD

**Issue by emersion** [GrapheneOS/Camera#150]
1. Scan e.g. https://fdroid.emersion.fr/
2. The text `fdroidrepos://fdroid.emersion.fr/…` is recognized, but isn't properly linkified.

Some apps use custom URL schemes to open directly activities. For instance, `fdroidrepos://` directly adds a new F-Droid repo.

**Comment by empratyush** [comment]
added in #297

**Comment by emersion** [comment]
Thanks!
