### ISSUE TITLE
Edit captured photo before it's saved

### ISSUE THREAD

**Issue by steve47457** [GrapheneOS/Camera#159]
How can I programmatically edit a captured photo before it's saved? For some reason, `onCaptureSuccess(image: ImageProxy)`  in the `takePicture()` method (line 116 - CaptureActivity.kt) is never called. Can someone provide clarification? Thanks.

**Comment by empratyush** [comment]
IMO you can do it on [ImageCapturer.kt](https://github.com/GrapheneOS/Camera/blob/main/app/src/main/java/app/grapheneos/camera/capturer/ImageCapturer.kt#L96)

**Comment by steve47457** [comment]
@empratyush Thank you for your reply. Can you please give an example? Because ImageCapturer.kt only has a `OnImageSavedCallback`.

**Comment by empratyush** [comment]
you need edit saved image afaict.

**Comment by steve47457** [comment]
@empratyush There's no way to edit the photo **before** it's saved?

**Comment by steve47457** [comment]
@thestinger What do you think?

**Comment by thestinger** [comment]
You should ask in the CameraX discussion group.

**Comment by steve47457** [comment]
@thestinger I think the issue is with your library because the CameraX functionality already exists (`OnImageCapturedCallback()`)

**Comment by thestinger** [comment]
We don't make a library.

**Comment by steve47457** [comment]
I meant the GrapheneOS Camera app. Is there way to treat the captured photo before it's saved? @thestinger

**Comment by steve47457** [comment]
In the same way the GrapheneOS Camera app can increase/decrease the brightness of a photo, is it not possible to edit the photo in other ways? @thestinger

**Comment by thestinger** [comment]
It doesn't have a way to increase/decrease brightness. It has a way to control the exposure settings with an exposure compensation slider. That's changing how much light is absorbed by the image sensor. It's much different than adjusting brightness and it isn't done after the photo is taken but rather as part of taken it.
