### ISSUE TITLE
RAW /capture storage

### ISSUE THREAD

**Issue by VulcanElf** [GrapheneOS/Camera#160]
Give the ability in settings to capture image as a RAW .CR2 file.  This is primarily aimed at Pixel 5 & 6, for their advanced cameras.

**Comment by Zanthed** [comment]
Already tracked in https://github.com/GrapheneOS/Camera/issues/14

**Comment by Entropy512** [comment]
I came here as a result of someone mentioning Graphene's camera app in a discussion of DNG compatibility issues, but to the original poster:

CR2 is a Canon-proprietary imaging format.  Any open source camera software would implement the DNG format.
