### ISSUE TITLE
[Question] release app on fdroid ?

### ISSUE THREAD

**Issue by Bugaddr** [GrapheneOS/Camera#161]
Thanks for this excellent app, is there any possibility (in near future) that this app will be released on fdroid (https://gitlab.com/fdroid) (https://f-droid.org) ? Or maybe hosted on any diffrent fdroid repository like (https://apt.izzysoft.de/fdroid) or any new repository by grapheneos ? Also if it's already hosted somewhere else (fdroid) please let me know !

**Comment by Zanthed** [comment]
No it won't be.

**Comment by thestinger** [comment]
The app is already released in our own app repository, which is not based on F-Droid.

**Comment by thestinger** [comment]
Look at the second section of the release notes: https://github.com/GrapheneOS/Camera/releases.

**Comment by Bugaddr** [comment]
> 

Thanks for the information sir.
