### ISSUE TITLE
support capturing new images while one is being saved

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Camera#180]

**Comment by thestinger** [comment]
Implemented.

**Comment by austinried** [comment]
I had imagined the solution to this would be related to #147, saving the image in a background task or something so it can't be interrupted, is this in version 25 on the beta channel as well?  I'm trying to take two images in a row and I still get the "please wait" message.

**Comment by thestinger** [comment]
There is no wait after the photo is captured on version 25. You still can't take a photo before the previous one you asked to capture is captured and will never be able to do that. If you want to speed up capture itself, you need to use Latency mode, and there is nothing for us to optimize there beyond CameraX adding support for ZSL, which likely wouldn't be used by Quality mode.
