### ISSUE TITLE
The setting button hided by status bar

### ISSUE THREAD

**Issue by haunt98** [GrapheneOS/Camera#184]
I use Xiaomi Poco X3 NFC. And the setting button in the app hided by status bar (the notch)

![Screenshot_2022-04-16-10-40-58-247_app.grapheneos.camera.play.jpg](https://user-images.githubusercontent.com/5424272/163660234-af2d135d-1a41-4d78-ac7d-6e25b76318e4.jpg)

**Comment by thestinger** [comment]
This is a bug in Xiaomi's OS and they appear to have addressed it with Android 12. You can open the settings by swiping down in the meantime.
