### ISSUE TITLE
make it visible when image is captured somehow

### ISSUE THREAD

**Issue by alexmo1997** [GrapheneOS/Camera#199]
currently, you can only see when an image has been saved in the gallery preview icon, but you can't see when the image has actually been taken (which can also take a second or so but is much faster than saving), so I have no idea when I can actually stop pointing the camera to the object i want to capture...
It would be nice if there could be some kind of visual feedback for this, I suppose there is already auditory feedback but I've got sounds disabled.

**Comment by thestinger** [comment]
There's both an animation and sound played after the image is captured so that's not correct.
