### ISSUE TITLE
Camera and Microphone Blocker

### ISSUE THREAD

**Issue by Pantyhose-X** [GrapheneOS/Camera#203]
Camera Blocker - Blocks general access to the camera from both installed apps and any external attempts.
Microphone Blocker – Effectively Blocks microphone usage, limiting it to phone calls and blocking out all external attempts as well.

# Why do we need Camera and Microphone Blocker
> Because my country in China is 1.4 billion people, we cannot buy open source or root mobile devices, and we have been monitored by the government and enterprises. System built -in camera and microphone have monitoring behaviors.

**Comment by Zanthed** [comment]
Both these toggles already exist in Settings -> Privacy -> Camera access & Microphone access
