### ISSUE TITLE
QR Scan support for front camera

### ISSUE THREAD

**Issue by oktay454** [GrapheneOS/Camera#212]
Hi
My phone's back camera is broken. I usually use the front camera
Please support QR scan for front camera

**Comment by MHShetty** [comment]
Hi @oktay454,

This issue has now been resolved in the latest changes pushed to the main branch (Reference commit: 101938bfa436aa51d4ddf19307be7753eff62716). The QR mode would now fallback to using front camera whenever rear camera isn't available for a given device. The changes should be visible in the next release or could alternatively be directly tested by building the app from the main branch of our repository.

Thanks a lot for making this feature request @oktay454!
