### ISSUE TITLE
Actions debug APK

### ISSUE THREAD

**Issue by xslvrxslwt** [GrapheneOS/Camera#231]
Maybe add a downloadable debug apk to GitHub [actions](https://github.com/GrapheneOS/Camera/actions)?

**Comment by Zanthed** [comment]
I don't really see why that's necessary.

**Comment by Zanthed** [comment]
We'd rather not have people run random debug APKs and report false bug reports/issues and make things confusing for alpha/beta testing.

**Comment by xslvrxslwt** [comment]
> I don't really see why that's necessary.

Already running actions, it's already there, just export the apk so we can use it before the actual stable release 😅

**Comment by thestinger** [comment]
It's not meant for people to use and we don't want issue reports from people testing the development branch.

**Comment by xslvrxslwt** [comment]
> It's not meant for people to use and we don't want issue reports from people testing the development branch.

Oh, okay, sorry
