### ISSUE TITLE
Documentation for installing this app

### ISSUE THREAD

**Issue by staticdev** [GrapheneOS/Camera#246]
I have checked out this app and I think it is great. Unfortunatelly, I have Android phones without GrapheneOS and I would very much like to install it.

Could you please add to README.md instructions to install it on normal Android phones?

**Comment by thestinger** [comment]
There's an explanation in the release notes:

https://github.com/GrapheneOS/Camera/releases

It can be installed from either the Play Store or our app repository. Our app repository client is available for Android 12+. We expect most people outside GrapheneOS to obtain it from the Play Store.

**Comment by staticdev** [comment]
@thestinger thanks for your response. Unfortunatelly, I still don't have access to Android 12. Also the link for Play Store does not work for me on Android 11. Does this app have a minimum requirement for Android 12?

**Comment by Zanthed** [comment]
Our Camera app works on Android 10 and above. What device are you on?

**Comment by staticdev** [comment]
Fairphone 4.

**Comment by thestinger** [comment]
Camera app supports Android 10 and later. Play Store release should work fine for you.

Our app repository client requires Android 12 or later.

**Comment by staticdev** [comment]
This is strange, I also tried with Aurora store, same result. It doesn't find the app by the link on release notes. Does it work for you?

**Comment by thestinger** [comment]
Yes, it's working fine. Which device model is it?

**Comment by thestinger** [comment]
I don't know why it wouldn't be working. Fairphone 4 is in the device catalog. Play Store says there are 21 users on it.
