### ISSUE TITLE
exif gps location not saved

### ISSUE THREAD

**Issue by lapoigne** [GrapheneOS/Camera#262]
Google Pixel 6
Build number : SQ3A.220605.009.B1.2022063000
Camera : version 43
remove EXIF data after capture : off 
location : enabled

I have enabled camera location and when I go to the photo detail I can't see the gps location on exif tags
I can see the app requesting location to the OS.

I do some tests with OpenCamera app:
 - If I use original camera API, location is saved on exif
 - If I use Camera2 API, location is not saved, like GrapheneOS camera app

**Comment by lapoigne** [comment]
Just got an update to version SQ3A.220705.003.A1.2022070600 and location is now saved

**Comment by trenfoight** [comment]
Im using pixel 7 pro and having same issue

**Comment by thestinger** [comment]
Have you enabled location and granted access to location? Test with GPSTest to see if you're getting a GNSS (satellite-based) location lock. If you're on GrapheneOS, there's only GNSS-based location for the OS location API, not network-based location, so it needs some time to get a lock.

**Comment by trenfoight** [comment]
GPS is on...im using phonetrack with my nextcloud server with no problem
