### ISSUE TITLE
Ability to set Camera to always default to Latency

### ISSUE THREAD

**Issue by novocaiin** [GrapheneOS/Camera#266]

**Comment by thestinger** [comment]
We have no plans to change how this works beyond eventually changing the default from Quality to Latency.

**Comment by novocaiin** [comment]
>The setting is persistent.

Yes, which means if it was previously set to Quality last time, it will still be on Quality when you reopen.

>eventually changing the default from Quality to Latency.

This is more or less what I'm asking for, defaulting to Latency.
