### ISSUE TITLE
Import QR scanned data

### ISSUE THREAD

**Issue by inpharmaticist** [GrapheneOS/Camera#270]
I think it would be convenient for the camera app QR scanner to have the option to detect/import certain formats. For example, a QR formatted as .vcf could show the option to `add to contacts`.

**Comment by jfrederickson** [comment]
Yeah - related, I just tried scanning a QR code for a wifi network, and was hoping for this to happen. (Most phones these days prompt you to join the network when you scan a QR code like that.)

**Comment by thestinger** [comment]
That feature is supported through the Wi-Fi add network QR scanner.

**Comment by jfrederickson** [comment]
Ah, that's good to know. Would still be convenient if the camera's QR code scanner could detect special formats like this though and send you to the right place automatically.

**Comment by empratyush** [comment]
see #389
