### ISSUE TITLE
File size storage issues

### ISSUE THREAD

**Issue by FlingCarnationProposal** [GrapheneOS/Camera#272]
When recording a video, the recording seems to be able to go on forever. However, when stopping the recording, it is only able to store 30 minutes or so at 1080p. The file size is approximately 4GB, so I think it is the filesystem limits that trims the video down to that length.

I think it is best if the user is given a warning before reaching the limit and either stop the recording if the limit is reached or split the video file into multiple files. The latter is preferred.

**Comment by thestinger** [comment]
> When recording a video, the recording seems to be able to go on forever. However, when stopping the recording, it is only able to store 30 minutes or so at 1080p. The file size is approximately 4GB, so I think it is the filesystem limits that trims the video down to that length.

On which device / OS?

> As an additional note, I think the encoding options should be tweaked to produce smaller file sizes, like changing the encoding format or the bitrate control mode (eg. CRF) and allowing the user to choose between presets that make sense (quality = high quality in CRF mode, file size = capped CRF). User controllable encoding settings is a nice bonus. I'm not sure if CameraX is blocking it though.

The only thing supported by CameraX is changing the resolution and it will use the device's recommended bitrate for that resolution with no way to change it.

**Comment by Zanthed** [comment]
It sounds like you're recording onto a FAT32 filesystem which does have a 4GB file limit. Not ext4.

**Comment by r3g-5z** [comment]
Merging into https://github.com/GrapheneOS/Camera/issues/287
