### ISSUE TITLE
aspect ratio stuck at 16:9

### ISSUE THREAD

**Issue by Soljanka** [GrapheneOS/Camera#273]
OS: Android 10 (LineageOS 17.1)
Device: Samsung Galaxy A3 (2017)
Camera Release 45 (from July 31)

I have the issue that the aspect ratio toggle does neither change the preview nor the actual photo. I am currently stuck at 16:9. Every photo I take has the same resolution (3264 x 1836) regardless of the aspect ratio I set. It's also odd since this phone does have a 12.8 MP camera; thus the resolution for 16:9 photos should be something like 4128 x 2322.
![43](https://user-images.githubusercontent.com/7444116/186245137-56eed960-9712-4ff0-95ba-df3f1486263c.png)
![169](https://user-images.githubusercontent.com/7444116/186245189-0bdf710a-123c-40a4-acfd-b996e7b31d37.png)

I downloaded Open Camera from F-Droid as a comparison and changing the aspect ratio here does have an effect.

**Comment by thestinger** [comment]
This is an issue with your OS / device, not GrapheneOS Camera. The issue will occur in other apps using CameraX too.
