### ISSUE TITLE
How do I add an icon to desktop? 

### ISSUE THREAD

**Issue by neil-timmerman** [GrapheneOS/Camera#284]
This is probably a dump question and I apologize for that...I learned that you can press the power button twice to open the camera app automatically. But, I'd like to also have a normal app icon on the desktop. How do I do that? I am transitioning from iOS for the past 7 years, so keep that in mind. Thank you!

**Comment by thestinger** [comment]
Please use https://discuss.graheneos.org/ for these kinds of questions.

There's one in the pinned bottom bar of the home screen by default. Maybe you removed it? All the apps are listed in the app drawer which you can drag to the home screen, but the camera app is already there in the pinned bar at the bottom by default. You're meant to put all the apps you actually use on your home screen(s) and app drawer is just a way to get the full list.
