### ISSUE TITLE
Edited images (GrapheneOS foto editor) are moved to subdirectory

### ISSUE THREAD

**Issue by indiDing** [GrapheneOS/Camera#288]
Pixel 6a, latest OS build (as of 2022-09-23)

GIVEN: shot an image with GrapheneOS camera app which is stored under the dedault folder /DCIM/Camera

WHEN I open the image with GrapheneOS camera app 
AND I push in the edit shortcut
AND I make any changes on the image within the GrapheneOS foto editor
AND I push the save button (to save my changes on the image)

THEN the editor app throws an error "An unexpected error occured after editing"
AND the original image will be moved to /DCIM/Camera/.aux folder (which was not existant before)
AND the modified image is not accessible by the camera app any more (but with another file explorer)

**Comment by thestinger** [comment]
GrapheneOS Camera includes an edit action to edit the image in an external editor app. There's no editor included in GrapheneOS Camera. I suggest that you install a different editor if you're having issues with AOSP Gallery. GrapheneOS doesn't make our own gallery app or image editor app.
