### ISSUE TITLE
Options notch in the wrong place

### ISSUE THREAD

**Issue by user1027** [GrapheneOS/Camera#304]
Phone: Redmi Note 8
Android: 10
Text size: "L"

The small arrow on the top of the screen that grows into some of the camera settings appears on the left. See video:

https://user-images.githubusercontent.com/112758742/195450991-cde98d1c-2645-402b-9fd3-8f28c663c292.mp4

**Comment by thestinger** [comment]
This is an issue with the OS providing the wrong information to the app if there isn't a notch blocking it from being in the middle. The status bar also shouldn't be shown on top of it. This works much better on newer Android versions without these vendor specific bugs for the most part.
