### ISSUE TITLE
Can't set it as default camera. 

### ISSUE THREAD

**Issue by KuroRagnar** [GrapheneOS/Camera#310]
I tried both apps, playstore and github release but it only list the stock camera.

Poco M3
MIUI global 12.5.9 (RJFMIXM)
Android 11

![Screenshot_2022-10-24-23-23-21-119_com android settings](https://user-images.githubusercontent.com/116618451/197684472-707e33ad-9aac-4da4-9cda-36812654c1b6.jpg)
![Screenshot_2022-10-24-23-23-32-832_com android settings](https://user-images.githubusercontent.com/116618451/197684479-673b659e-b2fc-4b50-9ba9-b7c7f1df1071.jpg)

**Comment by thestinger** [comment]
If you install a different 3rd party camera app such as Open Camera, does it get listed there?

**Comment by thestinger** [comment]
I think this is a bug in the OS and there's not much we can do about it. Would appreciate if you updated your review with the additional information since it doesn't seem it's an issue with our app.
