### ISSUE TITLE
Document recognition and pdf generation

### ISSUE THREAD

**Issue by BHydden** [GrapheneOS/Camera#317]
Some Samsung cameras can automatically detect when you're taking a picture of a document, outline the area of the paper, and convert the cropped/straightened/aligned image automatically to a .pdf file.

Would such a feature be in scope for this project down the line? If so what would it depend on? I have no idea about the complexity and technology involved, but it's a cool feature.

**Comment by thestinger** [comment]
No, it's not in scope for this project.

**Comment by thestinger** [comment]
OCR might be in scope at some point but not generating a PDF.
