### ISSUE TITLE
Black icons in Whatsapp file explorer (joining a picture)

### ISSUE THREAD

**Issue by Azertixe** [GrapheneOS/Camera#318]
Hello. When i go to send a picture in Whatsapp, i see black icons instead of thumbnails with pictures made with GrapheneOS Secure Camera.
➡️ It only happens when i choose SD card for default storage.
➡️ Icons back to normal after a restart. 
➡️ It's just a visual issue. I can join and open this pictures normally.
Any solution ?

Samsung Galaxy A3 2017
LineageOS 17.1
![Screenshot_20221102-173649_WhatsApp_1_1](https://user-images.githubusercontent.com/52431679/199557500-bf731121-6803-4a68-9e5c-8b24cfa0d5e7.png)

**Comment by thestinger** [comment]
This appears to be a bug in your OS. The media store isn't indexing files saved by SAF. It's possible we could set them to be indexed manually.

**Comment by Azertixe** [comment]
Hi. Thanks for your answer.
I haven't the bug using this camera :
https://www.celsoazevedo.com/files/android/google-camera/dev-greatness/f/dl9/
But I have the bug with Open Camera for example.

Le mer. 2 nov. 2022 à 20:06, Daniel Micay ***@***.***> a
écrit :
