### ISSUE TITLE
Feature request: Night Mode

### ISSUE THREAD

**Issue by Pauler221** [GrapheneOS/Camera#33]
Night mode would be great!

**Comment by MHShetty** [comment]
Yes, this should soon get implemented once those APIs get exposed for Pixel phones.

For more info.: https://developer.android.com/training/camerax/vendor-extensions

**Comment by Zanthed** [comment]
No need to close this @Pauler221. Issues are used to track feature requests too.

**Comment by elmo667** [comment]
@thestinger is there a way to track when this extension will be available? Im unfortunately not too familiar with all the moving parts (read: parties) here. So CameraX already supports this, so whom do we bug about this? Google?

**Comment by thestinger** [comment]
Pixels don't provide CameraX extensions yet. It works fine in CameraX and in our app. Our app has all 5 CameraX extensions available and working fine on Samsung phones.

**Comment by elmo667** [comment]
thanks, that helped. Found this to follow: https://issuetracker.google.com/issues/227166806
