### ISSUE TITLE
Camera Crash Pixel 6pro

### ISSUE THREAD

**Issue by Illusivemobile** [GrapheneOS/Camera#332]
I an getting the following errors even after reflashing the OS. I can't use my camera. Is there a fix for this???

t.d1
Camera is closed.
A  ::  t.c1  ::  89
z  ::  t.c1  ::  10
q  ::  t.c1  ::  14
p  ::  t.f2  ::  0
h  ::  z.g  ::  42
l  ::  z.g  ::  8
b  ::  androidx.camera.lifecycle.c  ::  49
v  ::  n2.p  ::  138
onClick  ::  t2.i  ::  565
performClick  ::  android.view.View  ::  7506
onTouch  ::  n2.k  ::  152
dispatchTouchEvent  ::  android.view.View  ::  15006
dispatchTransformedTouchEvent  ::  android.view.ViewGroup  ::  3115
dispatchTouchEvent  ::  android.view.ViewGroup  ::  2788
dispatchTransformedTouchEvent  ::  android.view.ViewGroup  ::  3143
dispatchTouchEvent  ::  android.view.ViewGroup  ::  2802
dispatchTransformedTouchEvent  ::  android.view.ViewGroup  ::  3121
dispatchTouchEvent  ::  android.view.ViewGroup  ::  2802
dispatchTransformedTouchEvent  ::  android.view.ViewGroup  ::  3121
dispatchTouchEvent  ::  android.view.ViewGroup  ::  2802
dispatchTransformedTouchEvent  ::  android.view.ViewGroup  ::  3121
dispatchTouchEvent  ::  android.view.ViewGroup  ::  2802
dispatchTransformedTouchEvent  ::  android.view.ViewGroup  ::  3121
dispatchTouchEvent  ::  android.view.ViewGroup  ::  2802
dispatchTransformedTouchEvent  ::  android.view.ViewGroup  ::  3121
dispatchTouchEvent  ::  android.view.ViewGroup  ::  2802
dispatchTransformedTouchEvent  ::  android.view.ViewGroup  ::  3121
dispatchTouchEvent  ::  android.view.ViewGroup  ::  2802
dispatchTransformedTouchEvent  ::  android.view.ViewGroup  ::  3121
dispatchTouchEvent  ::  android.view.ViewGroup  ::  2802
superDispatchTouchEvent  ::  com.android.internal.policy.DecorView  ::  500
superDispatchTouchEvent  ::  com.android.internal.policy.PhoneWindow  ::  1905
dispatchTouchEvent  ::  android.app.Activity  ::  4271
f  ::  d.u  ::  2
dispatchTouchEvent  ::  d.u  ::  0
dispatchTouchEvent  ::  com.android.internal.policy.DecorView  ::  458
dispatchPointerEvent  ::  android.view.View  ::  15269
processPointerEvent  ::  android.view.ViewRootImpl$ViewPostImeInputStage  ::  6650
onProcess  ::  android.view.ViewRootImpl$ViewPostImeInputStage  ::  6450
deliver  ::  android.view.ViewRootImpl$InputStage  ::  5906
onDeliverToNext  ::  android.view.ViewRootImpl$InputStage  ::  5963
forward  ::  android.view.ViewRootImpl$InputStage  ::  5929
forward  ::  android.view.ViewRootImpl$AsyncInputStage  ::  6094
apply  ::  android.view.ViewRootImpl$InputStage  ::  5937
apply  ::  android.view.ViewRootImpl$AsyncInputStage  ::  6151
deliver  ::  android.view.ViewRootImpl$InputStage  ::  5910
onDeliverToNext  ::  android.view.ViewRootImpl$InputStage  ::  5963
forward  ::  android.view.ViewRootImpl$InputStage  ::  5929
apply  ::  android.view.ViewRootImpl$InputStage  ::  5937
deliver  ::  android.view.ViewRootImpl$InputStage  ::  5910
deliverInputEvent  ::  android.view.ViewRootImpl  ::  8985
doProcessInputEvents  ::  android.view.ViewRootImpl  ::  8936
enqueueInputEvent  ::  android.view.ViewRootImpl  ::  8905
onInputEvent  ::  android.view.ViewRootImpl$WindowInputEventReceiver  ::  9108
dispatchInputEvent  ::  android.view.InputEventReceiver  ::  267
nativePollOnce  ::  android.os.MessageQueue  ::  -2
next  ::  android.os.MessageQueue  ::  335
loopOnce  ::  android.os.Looper  ::  161
loop  ::  android.os.Looper  ::  288
main  ::  android.app.ActivityThread  ::  7878
invoke  ::  java.lang.reflect.Method  ::  -2
run  ::  com.android.internal.os.RuntimeInit$MethodAndArgsCaller  ::  548
main  ::  com.android.internal.os.ExecInit  ::  49
nativeFinishInit  ::  com.android.internal.os.RuntimeInit  ::  -2
main  ::  com.android.internal.os.RuntimeInit  ::  355

**Comment by thestinger** [comment]
It sounds like your camera hardware is broken. Did you try a different camera app?
