### ISSUE TITLE
Bug: Video skips first seconds

### ISSUE THREAD

**Issue by secretmango** [GrapheneOS/Camera#342]
I was able to reproduce this twice.

I record a video normally and save it. 

Result:
First few milliseconds, maybe 0,25s show, then a big timeframe like 3s-15s are skipped and the video goes on normally until the end.

The complete video skips, together with audio, no black screen or overlapping audio, both are skipped exactly the same.

Pixel 4a, up to date apps.

**Comment by MHShetty** [comment]
Hi @firefoxlover,

This ideally shouldn't be happening. Could you please try reproducing the issue again while trying to record the logs during this time? This could possibly help us better understand where the issue currently lies.

Thanks for trying out our app and reporting this issue!

**Comment by MHShetty** [comment]
Hi @secretmango,

Could you please try testing our latest release for this issue?

Thanks a lot for your time and help!

**Comment by secretmango** [comment]
Seems to be fixed!

**Comment by MHShetty** [comment]
Glad to know that @secretmango

No issues at all, thanks a lot for reporting this issue and helping out with testing!
