### ISSUE TITLE
Add toggle for Mirror Selfie

### ISSUE THREAD

**Issue by aeoliam** [GrapheneOS/Camera#344]

**Comment by thestinger** [comment]
There's already a toggle for this in more settings.

**Comment by aeoliam** [comment]
i couldn't find it

![Screenshot_20230221-125620_Camera](https://user-images.githubusercontent.com/96276971/220259853-7765ff4d-6725-4fa4-b554-8c0e4fc2a5a1.png)

**Comment by thestinger** [comment]
Save image as previewed. We could make the wording clearer in the future.

**Comment by aeoliam** [comment]
Ah I see. Thanks for your help!

**Comment by aeoliam** [comment]
The saved picture is not mirrored even when the "Save image as previewed" option was on.

![Screenshot_20230223-182817_Spark Launcher](https://user-images.githubusercontent.com/96276971/220895784-8db626ca-99c5-4fe4-a584-5fa46194a9d3.png)
![IMG_20230223_182812_990](https://user-images.githubusercontent.com/96276971/220895763-609163c1-fc84-48f9-9d86-4f24af397f67.jpg)
![Screenshot_20230223-182836_Camera](https://user-images.githubusercontent.com/96276971/220895795-ce85a3e5-70c1-4b8a-8172-4bf095a09940.png)

**Comment by aeoliam** [comment]
The picture's saved is not mirrored in Gallery and other apps.

1. GrapheneOS Camera
![Screenshot_20230223-184547_Spark Launcher](https://user-images.githubusercontent.com/96276971/220897539-d0bab56b-4deb-47cb-9912-9f909426d86d.png)
![Screenshot_20230223-184721_Camera](https://user-images.githubusercontent.com/96276971/220898366-27f82936-c605-4008-9a4d-5ef71a680e2f.png)
2. QP Gallery
![Screenshot_20230223-184607_Gallery](https://user-images.githubusercontent.com/96276971/220897605-22b042ce-c19d-425e-b9e9-0117f82c84a5.png)
2. MiXplorer Image Viewer
![Screenshot_20230223-184630_MiXplorer](https://user-images.githubusercontent.com/96276971/220897627-6ce25dc0-c012-43c2-97d8-5ae83f5e4e73.png)

**Comment by thestinger** [comment]
EXIF orientation metadata isn't universally fully supported. This isn't an issue with our Camera app and it's not going to be implemented by post-processing the image and losing a lot of latency (it would also have to use 100% JPEG quality for the actual image capture then lower it to the configured value).
