### ISSUE TITLE
Make handling system microphone access block/unblock more user friendly

### ISSUE THREAD

**Issue by girlbossceo** [GrapheneOS/Camera#346]
Currently if your microphone access is blocked and you try to record with audio enabled, the camera will start recording (timer will start) and you will get a system notification to allow access to the microphone. Either allowing or disallowing the prompt will throw "error code 4" with the video recording failed to save, and you will need to manually unblock microphone access from the quick tile / settings.

See linked video recording (video recording is over 10MB). Could not find any Java exceptions or clear errors in logcat, but the line `02-22 20:21:01.362  1609 11226 E AppOps  : Operation not started: uid=10096 pkg=app.grapheneos.camera(null) op=RECORD_AUDIO` is very consistent when this happens.

https://photos.app.goo.gl/UtK9G2YaXbPkQH3RA

**Comment by r3g-5z** [comment]
The intended result should be not starting the recording until the user either unblocks or blocks it through the system prompt. If the user rejects it, the recording will cancel and a more user friendly snackbar should show saying the user needs to unblock microphone access or disable audio recording.

**Comment by r3g-5z** [comment]
Strange I wasn't able to find that, but yes that'd probably be the Camera app not handling that.
