### ISSUE TITLE
Autofocus seems disabled since last update (60)

### ISSUE THREAD

**Issue by raphaelyancey** [GrapheneOS/Camera#349]
I'm not sure this is linked but it seems pretty close. Anybody else experiencing this?

Tried to reboot with no effect. I could downgrade to confirm but I'm not sure how?

Thanks.

**Comment by thestinger** [comment]
The main change was updating to https://developer.android.com/jetpack/androidx/releases/camera#1.3.0-alpha04.

**Comment by raphaelyancey** [comment]
> Which device model?

Google Pixel 4a

> The main change was updating to https://developer.android.com/jetpack/androidx/releases/camera#1.3.0-alpha04.

Yes I'm sure this wasn't introduced intentionally :)

Just tried with Google Camera app and still no autofocus. I'm not quite familiar with how it works, is it a physical focus? What's the next step I should take to debug this?

**Comment by thestinger** [comment]
It doesn't sound like there's an issue with the camera app if it doesn't work in other apps. Autofocus is working fine on Pixel 4a with latest Beta release of GrapheneOS here. This sounds like a hardware failure now.
