### ISSUE TITLE
[Gallery] Save View Changes

### ISSUE THREAD

**Issue by kekkoudesu** [GrapheneOS/Camera#362]
This relates to the Gallery app.

You can switch between Grid view and Filmstrip View. I find Grid View annoying to navigate, so I like Filmstrip View, which is clearer. However, if I change it to Filmstrip View and go back to Albums, then back into the same folder, it will switch back to Grid View.

This should save my preference, or there should be an option for a default view preference.

Additionally, in an embedded view (like setting a wallpaper), you can *only* use the Grid View. You should be able to use the Filmstrip View.

**Comment by r3g-5z** [comment]
We're not taking feature requests for AOSP Gallery app. It's not our app and it needs to be replaced as it's very poor quality and ancient.
