### ISSUE TITLE
(Feature request) physical camera button support

### ISSUE THREAD

**Issue by Turbolqk** [GrapheneOS/Camera#379]
Hey guys, great camera app you have there! 
I'd like to ask if it's possible to add physical camera button support, like the ones on Sony devices etc.
I know your OS supports Pixel only, but your apps are used outside GrapheneOS itself too!
Thanks!

**Comment by empratyush** [comment]
what device you are on? we can add support for generic shutter(enter) button.

**Comment by Turbolqk** [comment]
Xperia Xz1 compact. It has a two-step button - half press for focus and full press to take a pic.

**Comment by empratyush** [comment]
I hope this extra camera button is generic button otherwise it would be impossible to utilize this.

**Comment by Turbolqk** [comment]
Well both LineageOs' Aperture and Open Camera utilize it, so its probably this.

**Comment by empratyush** [comment]
> Well both LineageOs' Aperture and Open Camera utilize it, so its probably this.

unsure about other apps. As i said earlier if it a generic button (which most likely it is) then it should be easy to add support for it.
