### ISSUE TITLE
Integrating Camera into Application

### ISSUE THREAD

**Issue by Dom00001** [GrapheneOS/Camera#407]
Firstly, I must express my admiration for your remarkable work on GrapheneOS' Camera. It's an impressive accomplishment, and I extend my heartfelt congratulations to the entire team.

As an independent app developer, I am exploring the possibility of integrating Camera into an application I am developing, with the intention of publishing it on the Google Play Store.

Upon reviewing the licensing information provided on your GitHub page, I understand that your software is distributed under the MIT License, which, to my knowledge, permits such use. However, I seek your confirmation to ensure complete compliance with your licensing terms.

Thank you for your time and assistance.

**Comment by thestinger** [comment]
It's MIT licensed. We would appreciate if you contributed improvements here though.
