### ISSUE TITLE
Choose photo quality

### ISSUE THREAD

**Issue by pluja** [GrapheneOS/Camera#41]
It would be nice to be able to choose a reduced photo quality to save space on the device.

**Comment by MHShetty** [comment]
Update -

Will be able to add this when this change is up in the next CameraX release
(https://android-review.googlesource.com/c/platform/frameworks/support/+/1810060)

**Comment by MHShetty** [comment]
This option has now been added in the more/advanced settings activity.

Thanks a lot for making this feature request @pluja!
