### ISSUE TITLE
capture location

### ISSUE THREAD

**Issue by cloudcoroner** [GrapheneOS/Camera#43]
other apps that may ask for access to captured media files are only given access to media folders such as DCIM. The camera app does not store its captured files in that location.

Use case: I installed a photo backup apk from my NAS vendor on grapheneos. Its file and media permissions are set to Allow access to media only. In the app, i can customize the backup source but can only see DCIM, DCIM -> OpenCamera, and Pictures. I cannot select Android/media/app.grapheneos.camera/Camera

**Comment by MHShetty** [comment]
I tried using this app, but it requires me to have some login credentials. But before we discuss more into that, I wanted to clarify something...

> Other apps that may ask for access to captured media files are only given access to media folders such as DCIM. The camera app does not store its captured files in that location.

We have made the required changes to ensure that the app only uses the DCIM storage (along with some other supporting changes). Does this resolve your issue?

**Comment by MHShetty** [comment]
> other apps that may ask for access to captured media files are only given access to media folders such as DCIM. The camera app does not store its captured files in that location.

The app now uses the device's default storage with the concept of scoped storage. That change has indirectly resolved this issue. Please do let us know if we misunderstood this issue by any chance.

Thanks a lot for reporting this issue!

**Comment by cloudcoroner** [comment]
I just downloaded and installed the alpha build that hit the repo a couple of hours ago. Storage location is accessible with media access privilege, confirmed this update has resolved the issue. Aside from that non-visible change, the visible updates to the app and its control panel look very nice.

**Comment by ezeeman** [comment]
I have release 2021102300 tag SP1A.210812.015.2021102300 installed on a pixel 4a. Photos taken by the camera are stored in <internal storage>/Pictures instead of <internal storage>/DCIM/Camera. This change in behavior started a week or two ago, I'm not certain which OTA release broke it.

**Comment by thestinger** [comment]
Release SP1A.210812.015.2021102300 uses AOSP Camera, not this app.

**Comment by thestinger** [comment]
AOSP Camera changed location for photos in AOSP 12. Nothing to do with this. It also wasn't a change made by GrapheneOS.

**Comment by ezeeman** [comment]
Thanks for the clarity, thestinger.

DCIM has been used for photos on phones for as long as I remember.

Is it just a coincidence that both the new GrapheneOS Camera app and the old AOSP 12 Camera app have just decided to store photos in a new, non-standard place? Or has some android spec changed, and the path is obtained by a system call, and that has changed. If so, all media, backup, and other apps that access photos have to be updated to accommodate user photos existing in two places now.

**Comment by thestinger** [comment]
That's not true. Read what was written. Stop posting off-topic stuff here.
