### ISSUE TITLE
Replace resize icon

### ISSUE THREAD

**Issue by dhishkyaon** [GrapheneOS/Camera#46]
Replace resize icon with ratio like this 👇🏾

![IMG_20211029_103932_543.jpg](https://user-images.githubusercontent.com/88529066/139379293-1b1666a7-949a-40ff-8f52-478f6a910a19.jpg)

**Comment by MHShetty** [comment]
Hi @dhishkyaon,

This issue has been resolved in the latest changes made to the source code (as seen above). Changes should be visible in the next release. 

Thanks a lot for suggesting this enhancement and for expressing your idea in the form of an image 😄
