### ISSUE TITLE
Camera app breaks until next unlock when doing lockscreen protected actions

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/Camera#48]
Steps to reproduce:

1 - Double tap power button to open Camera on lockscreen
2 - Take photo
3 - Tap preview to be taken to gallery, from there attempt to tap edit or share.
4 - The Camera app becomes unusable until next unlock

We should either remove the capability for these actions from the lockscreen or prompt for unlock before allowing them.

**Comment by MHShetty** [comment]
Hey @flawedworld,

Another user too faced issues with the edit/share option on a Pixel 3A (the app crashed on unlock), so I have disabled the editing/sharing option for now.

This issue has been resolved in this commit (by disabling the two options): https://github.com/GrapheneOS/Camera/commit/5dba05cdf94d02d6d70f6fee375c3ff92f8b9caa

Thanks a lot for reporting this issue!
