### ISSUE TITLE
Replacing the exposure icon with a more user-friendly brightness icon

### ISSUE THREAD

**Issue by dhishkyaon** [GrapheneOS/Camera#49]
since the app is going to be the default camera app in next week release, some UI changes are required so that app looks more user friendly.
something like this 👇🏾

![PicsArt_11-03-12.01.59~2.jpg](https://user-images.githubusercontent.com/88529066/140019316-f47f8632-0b28-4242-9110-818208952e21.jpg)

if you can do that for zooming scale too that would be great.

and also the settings closing animation need some work. It should disappear before it reaches the arrow. same goes for opening animation.

**Comment by MHShetty** [comment]
Hi @dhishkyaon,

The issue with changing the icon is that currently that seek bar doesn't really control the brightness of the image but rather the amount of light the camera is exposed to the camera (brightness != exposure). So having that icon over there could be misleading to the user. (For more information: https://www.lightxapp.com/difference-between-brightness-and-exposure/#:~:text=Brightness%20is%20simply%20how%20dark%20or%20light%20a%20picture%20is.&text=When%20clicking%20a%20picture%2C%20exposure,changing%20the%20camera%20settings%20beforehand.)

Please do let us know what you feel about the same.

Extremely sorry for the late reply and thanks a lot for letting us know about this possible enhancement and visually expressing your idea 😄
