### ISSUE TITLE
https://github.com/GrapheneOS/Camera/blob/f397284f266cafe164959172a5a31db34b5e3b89/app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt#L785

### ISSUE THREAD

**Issue by Harrispabayo2021** [GrapheneOS/Camera#50]
https://github.com/GrapheneOS/Camera/blob/f397284f266cafe164959172a5a31db34b5e3b89/app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt#L785

**Comment by thestinger** [comment]
Why are you linking this?
