### ISSUE TITLE
occasional video preview misalignment (does not impact recording)

### ISSUE THREAD

**Issue by thestinger** [GrapheneOS/Camera#54]
This appears to be a CameraX bug.

**Comment by MHShetty** [comment]
I have raised a issue regarding this to the CameraX team: https://issuetracker.google.com/issues/205326875

**Comment by MHShetty** [comment]
It seems that the issue has been accepted by someone from the CameraX team now.

**Comment by MHShetty** [comment]
This issue has now been resolved in the latest changes made to the source code
