### ISSUE TITLE
Automatic flash dark photos

### ISSUE THREAD

**Issue by TheReverend210** [GrapheneOS/Camera#55]
On at least Pixel 3a, setting flash to automatic results in dark photographs, as the second flash to light the scene doesn't trigger.

Setting flash to manually on and taking a photo will have a long flash for the autofocus to work, then a second shorter flash as the photo is taken.

Setting flash to auto and being somewhere dark enough to require the flash will have a long flash for the autofocus, but not then trigger the second flash whilst the photo is taken, resulting in a dark picture.

**Comment by MHShetty** [comment]
Hi @TheReverend210,

We are aware of this issue and have requested the CameraX team to fix this issue asap. Once they make the required changes and include it in a release, this issue should automatically get resolved as soon as we update to the latest version of the library.

Here's the link to the bug we had previously reported: https://issuetracker.google.com/issues/205373142
You can track the status of this issue from the above link.

Thanks a lot investigating and raising this issue @TheReverend210!

**Comment by MHShetty** [comment]
It seems they have found a fix for this issue and they are working on making the required code changes (the thread shared in the last message). 

Once they'll push the changes and include it in a release, this issue should get resolved on your end.

**Comment by MHShetty** [comment]
The new release unfortunately didn't fix this but they recently accepted the issue, so this should get fixed by the next official CameraX release. (https://issuetracker.google.com/issues/205373142#comment4)

**Comment by MHShetty** [comment]
Hi @TheReverend210,

This issue has now been addressed and fixed by the CameraX team. Changes should soon be visible as soon as they make a release and we update to the latest version of the library. (https://issuetracker.google.com/issues/205373142#comment8)

Thanks a lot for reporting this issue!

**Comment by MHShetty** [comment]
Hi @TheReverend210,

This issue has now been resolved in the latest CameraX release, however another issue seems to have cropped up after those changes. Will create and reference a separate issue for that (will need for CameraX to fix that again too).

Thanks a lot for reporting this issue and patiently waiting with us!
