### ISSUE TITLE
Save selfie as previewed

### ISSUE THREAD

**Issue by bugycugy** [GrapheneOS/Camera#56]
**Would you consider adding this feature?**

"Save pictures with the same orientation seen in the viewer."

**Comment by thestinger** [comment]
Flipping the image via EXIF is entirely possible just like how the orientation is set based on the device's rotation. It's entirely possible to do that on your own for the time being. The captured image is always in the same actual orientation with the metadata determining how it's shown.

**Comment by bugycugy** [comment]
> Flipping the image via EXIF is entirely possible just like how the orientation is set based on the device's rotation. It's entirely possible to do that on your own for the time being. The captured image is always in the same actual orientation with the metadata determining how it's shown.

I know the details but this feature comes in handy, I like your camera app very much. I am using it on my Mi Note 10 Pro (OctaviOS - A12). In my opinion, this is the only missing feature, so I wanted to convey it to you.

**Comment by MHShetty** [comment]
A persistent option has been added to prevent the flipping of image.  The changes have been pushed to the repository and the option should be visible for the front-camera in the next release.

Thanks a lot for requesting this enhancement @bugycugy!

**Comment by bugycugy** [comment]
> A persistent option has been added to prevent the flipping of image. The changes have been pushed to the repository and the option should be visible for the front-camera in the next release.
> 
> Thanks a lot for requesting this enhancement @bugycugy!

Thank you very much for adding this feature...
