### ISSUE TITLE
Camera's bottom tablayout is off center

### ISSUE THREAD

**Issue by JanOstrowka** [GrapheneOS/Camera#57]
![image](https://user-images.githubusercontent.com/3185243/140656882-338308e0-c18e-4593-8ef2-d57705f7746e.png)

When using the newly released camera app, I've noticed that navigation tabs ("QR SCAN", "CAMERA", "VIDEO") never seem to align properly and tend to float off center. Most of the time, when switching mode, tabs align in the center and then move abruptly, to the wrong place.

It is a very minor bug. I also would like to say, that this is a really welcome update, that has finally made the native Graphene OS camera usable. Thank you!

---

**Hardware**:
os: 2021110617
phone: Pixel 5

**Comment by MHShetty** [comment]
Hey @JanOstrowka,

The bottom tab layout needs to be worked upon/full re-designed in order to resolve this and some other issues related to it. We are working on this and will revert as soon as this gets fixed.

Thanks a lot for reporting this issue!

**Comment by bd0n4lds** [comment]
I see the same on different hardware.
Hardware:
os: 2021110617
phone: Pixel 4a

**Comment by MHShetty** [comment]
> I see the same on different hardware. Hardware: os: 2021110617 phone: Pixel 4a

This isn't a device/hardware specific issue. Any updates regarding this issue shall be posted here.

**Comment by MHShetty** [comment]
Hi @JanOstrowka,

This issue has been resolved in the latest changes pushed to the repository. Changes should be visible in the next release. 

Thanks a lot for reporting this issue!
