### ISSUE TITLE
Remember "Include Audio" toggle state

### ISSUE THREAD

**Issue by Ammako** [GrapheneOS/Camera#58]
The "Include Audio" toggle always returns back to On every time you start the camera app again. I think it would be helpful if it could stay off when turned off so you wouldn't have to manually turn it back off again every time.

That being said, I understand that it might be an issue if someone wanted to include audio in their recording, they might forget to re-enable the setting, and they'll only notice once it's too late. To avoid this problem I think there could be an icon on the UI indicating when Audio is being excluded, to remind people that they need to toggle the setting back on if they want to record audio.

Maybe the red "start recording" dot button could have a microphone icon inside it, with a slash across it, indicating that microphone is off? It would be impossible to miss it. I'm not sure how well it would fit though, the button might be a bit small.

**Comment by MHShetty** [comment]
> Maybe the red "start recording" dot button could have a microphone icon inside it, with a slash across it, indicating that microphone is off? It would be impossible to miss it. I'm not sure how well it would fit though, the button might be a bit small.

This seems to be a really good way to avoid the issue that was initially been taken into consideration. I'll work once I'm done with most of the other stuff that's currently pending.

Thanks a lot for suggesting this enhancement @Ammako!
