### ISSUE TITLE
I see the same on different hardware.

### ISSUE THREAD

**Issue by Harrispabayo2021** [GrapheneOS/Camera#59]
I see the same on different hardware.
Hardware:
os: 2021110617
phone: Pixel 4a

_Originally posted by @bd0n4lds in https://github.com/GrapheneOS/Camera/issues/57#issuecomment-963740572_

**Comment by MHShetty** [comment]
Hi,

The bottom tab layout issue isn't device/hardware specific and any updates regarding this issue shall directly be posted there.

Thanks for reporting this issue @Harrispabayo2021!
