### ISSUE TITLE
Record video as shown in preview

### ISSUE THREAD

**Issue by lmJojo** [GrapheneOS/Camera#61]
The video I recorded with my front-facing camera are always flipped. How can save it as previewed?

**Comment by thestinger** [comment]
You can do this by altering the metadata. Our Camera app doesn't support flipping it in the metadata yet.

**Comment by MHShetty** [comment]
Currently CameraX only supports altering metadata for the images it takes and unfortunately not video (the same reason why geo-tagging isn't supported for video yet). We might need to wait until they make the required changes and include it in one of their releases.

**Comment by joklmT** [comment]
Thank you for your answers. I get it.

**Comment by MHShetty** [comment]
Hi @lmJojo,

A small update related to this feature request -

The CameraX team seems to have considered this feature request (that was earlier made by another user) -
https://issuetracker.google.com/issues/194634656#comment9

We'll add this feature to our camera app as soon as CameraX supports it in one of their future releases.

Thanks a lot for making this feature request @ImJojo!

**Comment by GurucharanSavanth** [comment]
Thanks

On 24 May 2022 3:36:12 pm IST, Mohit Shetty ***@***.***> wrote:
>Hi @lmJojo,
>
>A small update related to this feature request -
>
>The CameraX team seems to have considered this feature request (that was earlier made by another user) -
>https://issuetracker.google.com/issues/194634656#comment9
>
>We'll add this feature to our camera app as soon as CameraX supports it in one of their future releases.
>
>Thanks a lot for making this feature request @ImJojo!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/GrapheneOS/Camera/issues/61#issuecomment-1135704200
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- Sent from /e/ Mail.

**Comment by r3g-5z** [comment]
CameraX now supports this as of [1.3.0-alpha06](https://developer.android.com/jetpack/androidx/releases/camera#1.3.0-alpha06)

> Added VideoCapture mirroring APIs, including VideoCapture.Builder.setMirrorMode(int) and VideoCapture.getMirrorMode(). The APIs are useful for applications require the video recording to be consistent with common camera preview behavior, i.e. the rear camera preview is not mirrored but the front camera preview is mirrored.

**Comment by lmJojo** [comment]
Thanks you.I will try it.

**Comment by thestinger** [comment]
We haven't added the feature yet.

**Comment by lmJojo** [comment]
Ok.I'm going to try it in my demo

**Comment by MHShetty** [comment]
The issue has been fixed in the PR mentioned above (#435)
