### ISSUE TITLE
Use higher bitrate for 4k video

### ISSUE THREAD

**Issue by Derkades** [GrapheneOS/Camera#67]
Currently, the GrapheneOS camera uses roughly the same bitrate for 4k and 1080p (~13Mbit/s) while Google Camera records at a more suitable 50Mbit/s

**Comment by MHShetty** [comment]
Hi @Derkades,

I have filed a feature request regarding to the CameraX team. (https://issuetracker.google.com/issues/207626321)
Hope this issue gets resolved by the next release 🤞

**Comment by thestinger** [comment]
This is resolved now.
