### ISSUE TITLE
The UI is off-center after v4

### ISSUE THREAD

**Issue by flexagoon** [GrapheneOS/Camera#68]
Here's how the UI looked before v4:
![Screenshot_20211122-175948_Camera](https://user-images.githubusercontent.com/66178592/142884208-deb68d72-cbe8-4bed-b896-3e27a1a00e5c.png)
And here's what it looks like now:
![Screenshot_20211122-180028_Camera](https://user-images.githubusercontent.com/66178592/142884325-526db4e2-bb57-45dd-9c73-babbac43dce5.png)
It's off center and there's a lot of unused space in the bottom

**Comment by thestinger** [comment]
On which device?

**Comment by flexagoon** [comment]
> On which device?

I have OnePlus 7T Pro.

**Comment by flexagoon** [comment]
Thanks!

**Comment by flexagoon** [comment]
@MHShetty unfortunately the issue still persists in v7

**Comment by thestinger** [comment]
Show a screenshot.

**Comment by flexagoon** [comment]
![Screenshot_20211202-093320_Camera](https://user-images.githubusercontent.com/66178592/144370190-b2b3786e-d5c7-42f9-9572-02db3fac54f0.png)
Its pretty much the same as it was

**Comment by flexagoon** [comment]
@thestinger @MHShetty could you please re-open this issue? I still have it.
