### ISSUE TITLE
Optional timestamp

### ISSUE THREAD

**Issue by Ammako** [GrapheneOS/Camera#70]
I think it would be nice if you could have the option to time stamp photos and videos. It would show up on the preview, so that what you see is what you get.

It would be useful for a lot of things. For example, I use this as my dash cam, and it would be nice to have exact date and time showing on the recordings, just in case.

**Comment by thestinger** [comment]
It does put a timestamp in the image / video metadata by default and a video player can use that to show the actual time. I think that makes this into a video player feature rather than a video one.
