### ISSUE TITLE
UI - button for settings menu is too high.

### ISSUE THREAD

**Issue by ASerbinski** [GrapheneOS/Camera#73]
Since the settings button was moved closer to the top of the screen, its position has become a problem on devices with a centered hole punch style camera such as Pixel 6 Pro. The button now appears exactly where the camera is.

See the following issue for screenshots of how the button has moved closer to the top of the screen: https://github.com/GrapheneOS/Camera/issues/68

**Comment by thestinger** [comment]
This is being worked around via the latest development branch changes.
