### ISSUE TITLE
Add support for Ultra-Wde lens , please.

### ISSUE THREAD

**Issue by Adam-718** [GrapheneOS/Camera#85]
I tested this apk(version 8) on my Asus Zenfone 8 running LinageOS. it works perfectly,
Just wish it supports the Ultra-Wide camera of the phone as well.

Great job guys, please keep the code rolling!!

**Comment by thestinger** [comment]
It has support for it on devices implementing it the same way Pixels do. If they don't do that then it's likely not going to be supported.

**Comment by thestinger** [comment]
One day we might support cycling through alternate cameras which would make it work with this kind of device. Pixels switch automatically based on zoom level.
