### ISSUE TITLE
3:2 aspect ratio

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/Camera#89]
This was requested by a user.

**Comment by MHShetty** [comment]
Hey @flawedworld,

We'll need to wait for CameraX to support it and to be able to support 3:2 aspect ratio. (We have filed an feature request for the same that can be tracked from here: https://issuetracker.google.com/issues/213757975.)

Thanks a lot for filing this feature request!

**Comment by MHShetty** [comment]
They're asking for more information regarding the same (like what are the use cases for 3:2 etc.). 

Could you please ask the user about the same?

**Comment by flawedworld** [comment]
3:2 aspect ratio is a standard aspect ratio used in the majority of standalone digital cameras.

**Comment by MHShetty** [comment]
Hi @flawedworld,

I have mentioned this use-case there and there are a few more new messages there. It might take a while before this gets implemented, but it seems that they have accepted our feature request.

Thanks a lot for filing this feature request!

**Comment by lbdroid** [comment]
I don't see how this could actually be "blocked on CameraX". The native sensor resolution is going to be 4:3, therefore to achieve 3:2 aspect ratio, or for that matter ANY other aspect ratio, would involve cropping the preview and output images. While the HAL and/or CameraX would be responsible for cropping normally, it is something that can easily be done by the application as well.

**Comment by thestinger** [comment]
Seems to too niche.

**Comment by thestinger** [comment]
Image capture cropping can already be done with the available CameraX APIs. Video capture doesn't have the necessary APIs yet. I don't really see much point in a purely software implementation of 3:2. The advantage of being able to use hardware support would be better performance. The native image sensor resolution isn't necessarily 4:3 but I'm not sure how common other aspect ratios would be. Video oriented devices may have a wider native aspect ratio but it's likely going to be wider than 3:2. 3:2 seems quite niche and I'm unsure why it's being requested specifically. We can consider supporting other aspect ratios in the future but for the time being I see little reason to add support for arbitrary aspect ratios without a way to use hardware support.

**Comment by thestinger** [comment]
It also needs to be clarified whether they're requesting it for image capture, video capture or both of them. It's not at all the same.
